### ISSUE TITLE
Digital Downloads

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#155]
### Description
We should add support for digital downloads so that the customer gets to download a file or something once they purchase a digital products.

This feature could also add things like license keys for bits of software that could be distributed. That's something that would be randomly generated and assigned to the order.

**Comment by ryangjchandler** [comment]
I think the concept of a Digital Downloads product type is perfect, but there shouldn't be any hard implementation in core. Instead, I think there should be some sort of event fired when the product is purchased so that the developer can hook in and generate license keys, or PDFs etc. By default, I guess it would be a simple file download.

**Comment by duncanmcclean** [comment]
I agree. Digital Downloads should be another package and not included in the core product offering.

There's already an event that gets fired when a successful checkout happens that could be listened to by another package.

**Comment by duncanmcclean** [comment]
I've made a start on building a [digital products addon](https://github.com/doublethreedigital/sc-digital-products) for Simple Commerce. 

Right now, all that's implemented is the ability to generate license keys and for the customer to be emailed after purchase with links to digital product downloads. 

There's still a few bits and bobs that need to be done until it's finished, like a MaxMind integration and a download history feature so store owners can see when customers have downloaded purchased items.
