### ISSUE TITLE
Post-sales email follow up

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#208]
## Describe the feature
After a sale, it would be nice to know that the customer has been successful in using the product. It would be nice to automatically send a series of follow up emails after they've had time to use it. This would have to be *product specific* in order to include relevant help articles, videos, etc.

**Comment by duncanmcclean** [comment]
Thanks for the issue.

Again, I'm thinking that this sort of feature would likely be included in a separate addon.

**Comment by duncanmcclean** [comment]
Following up on this issue now.

Like I mentioned in the other issue regarding marketing email lists, #220, unfortunately this is not something I'm planning on implementing as part of the addon and rather would probably be better fit for another addon or something custom built for your specific use-case.

By the sounds of things, you might want to listen onto the `CartConfirmed` event emitted by Simple Commerce and ping a webhook or whatever you need to do in order to add the customer to a drip marketing list.
