### ISSUE TITLE
Handle weight and dimensions to shipping rates

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#214]
## Describe the feature

As a core feature of simple-commerce, **weight** and **dimensions** should be part of the Product fields.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/27975/78887014-731d4000-7a5f-11ea-9a6a-231b10dc19c8.png">

Current shipping rate system is based on the postal_code / country. But in France, as an example, shipping rates depends directly of the package Weight (and also dimensional weight when shipping outside Europe):

<img width="478" alt="image" src="https://user-images.githubusercontent.com/27975/78885843-8b8c5b00-7a5d-11ea-89ee-d717ff9f4eb2.png">

We should be able:
- To fill weight and dimensions in the CP
- To configure the default weight unit for display in simple-commerce config
- To provide a custom ShippingMethodProvider that implements some methods to calculate the shipping rate (using Raw weight or Dimensional weight)

The Cart model should use a default ShippingMethodProvider to calculate the shipping price.

## Package dimensions in others e-commerce systems

In Stripe (removed in production, on 7 april 2020)

https://stripe.com/docs/orders/shipping-integration
<img width="750" alt="image" src="https://user-images.githubusercontent.com/27975/78885510-0bfe8c00-7a5d-11ea-9209-03178116bae3.png">

In Shopify:

<img width="512" alt="image" src="https://user-images.githubusercontent.com/27975/78886663-e6728200-7a5e-11ea-809c-a97f80bd2b34.png">

Others references:
- https://help.shopify.com/en/manual/shipping/understanding-shipping/packaging-and-weights#dimensional-weight
- https://help.oberlo.com/en/articles/1003820-how-to-add-weight-to-product-variants
- https://verbb.io/craft-plugins/postie/features

**Comment by duncanmcclean** [comment]
You can add your own fields to the product and variant pages. You should be able to add them in the provided fieldsets (not blueprints).

I know that weight and height are probably common for e-commerce stores but I don't want to provide them out of the box because some stores won't sell physical products.

I do agree that the shipping stuff should be more dependent on products for things like weight and height fields.

Do you think implementing something like what you suggested with the shipping method providers is something you could do (via pull request)? I'm a little busy trying to get other things like discounting built and fixing various bugs.

**Comment by duncanmcclean** [comment]
Alright, I'm glad to say that setting up shipping rates based on the weight of variants is something that's coming in the next release, along with the new cart system.

The implementation won't be as complex as having different shipping method providers, trying to keep to the name of the addon, 'Simple Commerce' haha.

✨ Here's a sneak peak of what the 'New Shipping Zone' stack will look like:

![image](https://user-images.githubusercontent.com/19637309/79510939-39879e80-8036-11ea-8558-703469783bcb.png)

**Comment by duncanmcclean** [comment]
Finished building, coming in next release.
