### ISSUE TITLE
Can't Install. Docs not clear

### ISSUE THREAD

**Issue by sebszocinski** [duncanmcclean/simple-commerce#221]
Followed all the steps to install but got an error here when running :
`php artisan vendor:publish --provider=DoubleThreeDigital\SimpleCommerce\ServiceProvider`

Result:
```
Unable to locate publishable resources.
Publishing complete.
```

The next step `Also make sure to add the IsACustomer trait to your User model and add the following code:` isn't clear to me. Perhaps elaborate on this?

And the example code below it has a syntax error, the first `$fields` array is missing a closing `]`;

I was able to get the database setup and seeded, and I can see the Products and Orders screens in the CP but the Settings link breaks giving me an error which I assume is related to the `IsACustomer` thing above?

**Comment by duncanmcclean** [comment]
Thanks for your issue!

Just pushed out some updated documentation for the install process. I wrote the previous revision in a hurry, really should have rewritten sooner.

Turns out the publishing command was missing some quotes, so this should work:

```
php artisan vendor:publish --provider="DoubleThreeDigital\SimpleCommerce\ServiceProvider"
```

Regarding the other steps, you should be able to [review them here](https://github.com/doublethreedigital/simple-commerce#installation).
