### ISSUE TITLE
Refresh after successful purchase

### ISSUE THREAD

**Issue by Hesesses** [duncanmcclean/simple-commerce#270]
Refreshing the checkout page gives error:
```
TypeError
Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Repositories\CartRepository::find() must be of the type string, null given, called in /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261
```

**Comment by duncanmcclean** [comment]
Fixed in next release. The recommended method is to add the `redirect` param to the `{{ sc:checkout }}` tag to go to an order success page of your choice.

```
{{ sc:checkout redirect="/thanks" }}
   ...
{{ /sc:checkout }} 
```

Unfortunately, it's no longer possible to use order data in the order success page because we can't give the session the order ID for more than 1 request and there's not really a way for us to persist it that it wouldn't conflict with the customer purchasing more products.
