### ISSUE TITLE
Adding item to cart error

### ISSUE THREAD

**Issue by sebabal** [duncanmcclean/simple-commerce#287]
I updated to the latest version 2.0.10 and I am getting a (when trying to add an item to the cart):

`Target [DoubleThreeDigital\SimpleCommerce\Contracts\ProductRepository] is not instantiable.`

Here is the full stack trace: https://flareapp.io/share/KPgAre5a

Here is the "Add to Cart" form:

```html
<div x-data="{ quantity: 1, loading: false }">
	{{ sc:cart:addItem redirect="/cart" class="flex flex-col" }}
	<input type="hidden" name="product" value="{{ id }}">
	<input type="hidden" name="quantity" value="1">

	<div class="flex flex-row items-stretch w-full my-2 px-6">
		{{ if stock === 0 }}
		<p class="text-red-600 font-semibold">Out of stock</p>
		{{ else }}
		<button x-show="loading === true"
			class="draw-border-tertiary-2 ml-auto py-2 px-6 uppercase text-white font-bold flex flex-row items-center justify-center"
			type="button">
			<i class="fal fa-spinner-third fa-spin mr-2"></i> Adding
		</button>
		<button x-show="loading === false" class="draw-border-white-2 ml-auto py-2 px-6 uppercase text-white font-bold"
			type="button" x-on:click="loading = true; document.forms[0].submit()">
			<i class="fal fa-cart-plus mr-2"></i> Add to Cart
		</button>
		{{ /if }}
	</div>
	{{ /sc:cart:addItem }}
</div>
```

## Environment

Statamic 3.0.0 Pro
Laravel 6.18.35
PHP 7.4.3
aryehraber/statamic-recaptcha dev-statamic-3
doublethreedigital/duplicator 1.0.5
doublethreedigital/simple-commerce 2.0.10
statamic/migrator dev-master

**Comment by duncanmcclean** [comment]
Can you confirm if the `ProductRepository` file exists? It should be in your `vendor/doublethreedigital/simple-commerce/src/Contracts` folder.

We changed some stuff to do with how the repositories are bound to the Laravel container in that recent update so that might be causing issues. We also weren't using the `ProductRepository` interface on the product repository before so that could also be the issue, especially if it seems to work for the other repositories.

**Comment by duncanmcclean** [comment]
Nevermind, I can replicate. I'll get that fixed.

**Comment by duncanmcclean** [comment]
Turns out I can't spell. Since it's a big issue, I'll tag a new release in the next few minutes which should sort it. Sorry about this.
