### ISSUE TITLE
Allow the use of statamic Globals inside order-confirmation.blade.php

### ISSUE THREAD

**Issue by studiovlijmscherp** [duncanmcclean/simple-commerce#418]
We need the order-confirmation.blade.php to contain a (via /cp ) configurable text.

Tried using 

```
Dear {{ $order['customer']->value()->data()->get('name') }}, <br>
<br>
{{ client-e-mail:content }}
```

Where {{ client-e-mail:content }} is a configurable Statamic Global
But... we cannot use Antlers inside blade. Some way to get this to work?

**Comment by duncanmcclean** [comment]
Globals aren't passed in as variables but you can probably just use it via the `GlobalSet` facade. You should be able to do something like this:

```
{{ \Statamic\Facades\GlobalSet::find('name-of-set')->in('default')->get('email-content-text') }}
```

**Comment by duncanmcclean** [comment]
In v2.3 (which I've just tagged the first beta for), the order confirmation email will become a Laravel notification, rather than a Mailable, so you'll be able to pass whatever you want into the email views.

Here's the [full changelog](https://github.com/doublethreedigital/simple-commerce/blob/2.3/CHANGELOG.md#v230-2021-xx-xx) if you're interested.
