### ISSUE TITLE
Inconsistent price value output when `tax.included_in_prices` is set to `true`

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#427]
If you set `tax.included_in_prices` to `true`, the product prices output the tax inclusive value as expected, but in the basket the line item `total` and cart `items_total` output the tax exclusive value.

I think it it would make sense if these were consistent. At the moment, if you just output the price values as provided by Simple Commerce it's rather confusing:

![Screenshot 2021-06-08 at 14 08 10](https://user-images.githubusercontent.com/126740/121190487-05d38d80-c863-11eb-9d0e-ec26eb23ca64.png)

I'd suggest matching the cart values to the price configuration. So if `tax.included_in_prices` is `true`, the line item `total` and cart `items_total` values should also be calculated with tax include.

This is not a problem when `tax.included_in_prices` is `false`, as everything is output as tax exclusive already.

In addition to making the values consistent, it might also be useful to include an additional set of properties that provide the opposite values to whatever `tax.included_in_prices` is set to. I can see a situation where a store owner might want to enter prices in CP exclusive of tax, but have them output on the site with tax, so additional `price_inc_tax`, `total_inc_tax` etc. properties would be useful. Likewise for `price_exc_tax`, `total_exc_tax` etc.

## Environment

Statamic 3.1.18 Pro
Laravel 8.45.1
PHP 7.4.16
doublethreedigital/simple-commerce 2.3.3

**Comment by duncanmcclean** [comment]
I think in order to achieve this we'll need to change the way we calculate tax. Instead of calculating it on the order as a whole, like we do now. We'll need to calculate it per line item instead.

I honestly don't know why I didn't do this to start off with, makes way more sense and gives you granular control over tax rates etc.

I think we may have to wait until v2.4 is in development to fix this as updating the `Calculator` contract would require a breaking change for anyone who overrides the `Calculator` interface..

**Comment by duncanmcclean** [comment]
This will be fixed as part of the new tax system I mentioned in [#428 ](https://github.com/doublethreedigital/simple-commerce/issues/428#issuecomment-867521386).

**Comment by duncanmcclean** [comment]
Closing as I believe this will also be fixed as part of the new tax system.

**Comment by duncanmcclean** [comment]
Oh by the way, this should be fixed on the current version of Simple Commerce too - someone recently submitted a PR to fix it. 🙂
